# See: https://github.com/NixOS/nix
if [ -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]; then
    source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
fi

# See: https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html
if [[ "${TERM}" =~ ^(dumb|linux)$ ]]; then
    unsetopt zle
    # unsetopt prompt_cr
    # unsetopt prompt_subst
    # unfunction precmd
    # unfunction preexec
    PS1="$ "
    return
fi

# See: https://github.com/zplug/zplug
if [ -f "${HOME}/.zplug/init.zsh" ]; then
    source "${HOME}/.zplug/init.zsh"

    zplug "zimfw/zimfw", \
        hook-build:"ln -sfvn ${ZPLUG_REPOS}/zimfw/zimfw ${HOME}/.zim"

    export ZSH_PLUGINS_ALIAS_TIPS_TEXT="☼ "
    zplug "djui/alias-tips"

    PREZTO_MODULES=(node python ruby)
    zplug "sorin-ionescu/prezto", \
        use:"modules/{${(j:,:)PREZTO_MODULES}}/init.zsh"

    zplug "${HOME}/.zsh", \
        from:local

    if ! zplug check --verbose; then
        printf "Install Zsh plugins? [y/N]: "
        if read -rq; then
            echo; zplug install
        fi
    fi

    zplug load
fi
