---

- name: "clone the gpakosz/.tmux repository"
  git:
    repo: "https://github.com/gpakosz/.tmux"
    dest: "~/.tmux"

- name: "link the .tmux/.tmux.conf file"
  file:
    src: "~/.tmux/.tmux.conf"
    dest: "~/.tmux.conf"
    state: "link"
