let
  nixpkgs = import <nixpkgs> {};
  default =
    [
      nixpkgs.aria2
      nixpkgs.bat
      nixpkgs.coreutils
      nixpkgs.cowsay
      nixpkgs.emacs
      nixpkgs.exa
      nixpkgs.exiftool
      nixpkgs.fd
      nixpkgs.fdupes
      nixpkgs.ffmpeg
      nixpkgs.git
      nixpkgs.gnupg
      nixpkgs.gnused
      nixpkgs.graphicsmagick
      nixpkgs.hexyl
      nixpkgs.htop
      nixpkgs.ipcalc
      nixpkgs.iperf
      nixpkgs.ispell
      nixpkgs.jq
      nixpkgs.jre
      nixpkgs.jrnl
      nixpkgs.mediainfo
      nixpkgs.mosh
      nixpkgs.mpv
      nixpkgs.mtr
      nixpkgs.ncdu
      nixpkgs.neofetch
      nixpkgs.nix
      nixpkgs.nmap
      nixpkgs.p7zip
      nixpkgs.pass
      nixpkgs.peco
      nixpkgs.postgresql
      nixpkgs.rclone
      nixpkgs.ripgrep
      nixpkgs.shellcheck
      nixpkgs.tmux
      nixpkgs.tree
      nixpkgs.vim
      nixpkgs.watch
      nixpkgs.wireguard-tools
      nixpkgs.yarn
    ];
in
  default
