[theme]
name = "gruvbox-dark"

[icons]
name = "awesome"

# [icons.overrides]
# cpu = " \uF3FD "

[[block]]
block = "backlight"

[[block]]
block = "temperature"
interval = 5
collapsed = false

[[block]]
block = "memory"
interval = 5
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
format = "{1m} {5m}"
interval = 2

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "net"
interval = 2
device = "wlp1s0"
graph_down = true
ssid = true

[[block]]
block = "sound"
driver = "alsa"

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = "{percentage}% ({power}W)"

[[block]]
block = "time"
interval = 60
