[theme]
name = "gruvbox-dark"

[icons]
name = "awesome"

# [icons.overrides]
# cpu = " \uF3FD "

[[block]]
block = "pomodoro"

[[block]]
block = "backlight"

[[block]]
block = "temperature"
interval = 5

[[block]]
block = "memory"
interval = 5
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "net"
interval = 2
device = "wlp59s0"

[[block]]
block = "sound"
driver = "alsa"

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = "{percentage}% ({power}W)"

[[block]]
block = "time"
interval = 5
