---

import:
  - "~/.config/alacritty/colorscheme.yml"

window:
  padding:
    x: 10
    y: 10

scrolling:
  history: 0

font:
  size: 12.0

hints:
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: "xdg-open"
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: "U"
        mods: "Control|Shift"

mouse_bindings:
 - mouse: "Middle"
   action: "None"
