---

- name: "clone the nodenv/nodenv repository"
  git:
    repo: "https://github.com/nodenv/nodenv"
    dest: "~/.nodenv"

- name: "clone the nodenv/node-build repository"
  git:
    repo: "https://github.com/nodenv/node-build"
    dest: "~/.nodenv/plugins/node-build"
