---

- name: "clone the yyuu/pyenv repository"
  git:
    repo: "https://github.com/yyuu/pyenv"
    dest: "~/.pyenv"

- name: "clone the yyuu/pyenv-virtualenv repository"
  git:
    repo: "https://github.com/yyuu/pyenv-virtualenv"
    dest: "~/.pyenv/plugins/pyenv-virtualenv"
