---

- name: "clone the rbenv/rbenv repository"
  git:
    repo: "https://github.com/rbenv/rbenv"
    dest: "~/.rbenv"

- name: "clone the rbenv/ruby-build repository"
  git:
    repo: "https://github.com/rbenv/ruby-build"
    dest: "~/.rbenv/plugins/ruby-build"
